# Generated by Django 2.2.4 on 2023-12-03 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fav_books', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='book',
        ),
    ]
